/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ee0000",
        "on-tertiary-fixed": "#2b0052",
        "surface": "#f9f9f9",
        "on-secondary-container": "#fefcff",
        "surface-dim": "#dadada",
        "canvas-soft-2": "#f5f5f5",
        "hairline-strong": "#a1a1a1",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474746",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "canvas": "#ffffff",
        "canvas-soft": "#fafafa",
        "hairline": "#ebebeb",
        "outline": "#747878",
        "on-surface-variant": "#444748",
        "secondary-fixed-dim": "#aec6ff",
        "secondary": "#0057c0",
        "on-tertiary": "#ffffff",
        "warning": "#f5a623",
        "on-tertiary-fixed-variant": "#6600b7",
        "tertiary-fixed-dim": "#dbb8ff",
        "inverse-primary": "#c8c6c5",
        "background": "#f9f9f9",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "ink": "#171717",
        "on-secondary-fixed-variant": "#004397",
        "primary-container": "#1c1b1b",
        "tertiary": "#000000",
        "tertiary-container": "#2b0052",
        "surface-variant": "#e2e2e2",
        "on-background": "#1a1c1c",
        "on-primary-container": "#858383",
        "on-error-container": "#93000a",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#001a43",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-container": "#006ff0",
        "secondary-fixed": "#d8e2ff",
        "body-text": "#4d4d4d",
        "on-tertiary-container": "#a75dfa",
        "outline-variant": "#c4c7c7",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#5f5e5e",
        "pink": "#ff0080",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "tertiary-fixed": "#efdbff",
        "mute": "#888888",
        "cyan": "#50e3c2",
        "on-surface": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "surface-container-high": "#e8e8e8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "6xl": "128px",
        "4xl": "64px",
        "xl": "32px",
        "max-width": "1400px",
        "xxs": "4px",
        "xs": "8px",
        "section": "192px",
        "lg": "24px",
        "3xl": "48px",
        "5xl": "96px",
        "2xl": "40px",
        "md": "16px"
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
      fontFamily: {
        "body-lg": ["geist", "sans-serif"],
        "body-md": ["geist", "sans-serif"],
        "display-md": ["geist", "sans-serif"],
        "caption": ["geist", "sans-serif"],
        "body-sm": ["geist", "sans-serif"],
        "body-md-strong": ["geist", "sans-serif"],
        "display-xl": ["geist", "sans-serif"],
        "code": ["geistMono", "monospace"],
        "display-sm": ["geist", "sans-serif"],
        "caption-mono": ["geistMono", "monospace"],
        "display-xl-mobile": ["geist", "sans-serif"],
        "display-lg": ["geist", "sans-serif"],
        "body-sm-strong": ["geist", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0px", fontWeight: "400" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.96px", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", letterSpacing: "0px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "-0.28px", fontWeight: "400" }],
        "body-md-strong": ["16px", { lineHeight: "24px", letterSpacing: "0px", fontWeight: "500" }],
        "display-xl": ["48px", { lineHeight: "48px", letterSpacing: "-2.4px", fontWeight: "600" }],
        "code": ["13px", { lineHeight: "20px", letterSpacing: "0px", fontWeight: "400" }],
        "display-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.6px", fontWeight: "600" }],
        "caption-mono": ["12px", { lineHeight: "16px", letterSpacing: "0px", fontWeight: "400" }],
        "display-xl-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-1.28px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-1.28px", fontWeight: "600" }],
        "body-sm-strong": ["14px", { lineHeight: "20px", letterSpacing: "-0.28px", fontWeight: "500" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

module.exports = config;
